name: Release Package to GitHub Registry
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_REPO_ACCESS_TOKEN }}
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: 14
      - uses: tianhaoz95-actions/dot-npmrc@v1.1.2
        with:
          org: "wowlink"
          token: ${{ secrets.GH_PKG_UPLOAD_TOKEN }}
      - name: Build package
        run: npm ci && npm run build
      - run: npx semantic-release
        env:
          GIT_AUTHOR_NAME: ${{ secrets.GIT_ACT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_ACT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_ACT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_ACT_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GH_PKG_UPLOAD_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_PKG_UPLOAD_TOKEN }}
